"""todo_table_remove_author

Revision ID: 792210e9b4c7
Revises: c3bb991f1247
Create Date: 2020-04-16 11:44:19.469767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '792210e9b4c7'
down_revision = 'c3bb991f1247'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('author', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
