"""todo_table_add_index

Revision ID: c3bb991f1247
Revises: de7758c574dd
Create Date: 2020-04-16 11:18:59.761640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3bb991f1247'
down_revision = 'de7758c574dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('body', sa.String(length=256), nullable=True))
    op.create_index(op.f('ix_todo_created_at'), 'todo', ['created_at'], unique=False)
    op.drop_constraint('todo_author_key', 'todo', type_='unique')
    op.drop_constraint('todo_created_at_key', 'todo', type_='unique')
    op.drop_constraint('todo_description_key', 'todo', type_='unique')
    op.drop_constraint('todo_time_end_key', 'todo', type_='unique')
    op.drop_constraint('todo_topic_key', 'todo', type_='unique')
    op.drop_column('todo', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('description', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.create_unique_constraint('todo_topic_key', 'todo', ['topic'])
    op.create_unique_constraint('todo_time_end_key', 'todo', ['time_end'])
    op.create_unique_constraint('todo_description_key', 'todo', ['description'])
    op.create_unique_constraint('todo_created_at_key', 'todo', ['created_at'])
    op.create_unique_constraint('todo_author_key', 'todo', ['author'])
    op.drop_index(op.f('ix_todo_created_at'), table_name='todo')
    op.drop_column('todo', 'body')
    # ### end Alembic commands ###
